### ISSUE TITLE
[Bug]: client.guilds.has is not a function

### ISSUE THREAD

**Issue by BeeBuzz420** [ItsDizzy/commando-provider-mongo#12]
client.guilds.has is not a function

```
TypeError: client.guilds.has is not a function
2020-12-11T04:17:37.521234+00:00 app[worker.1]:     at /app/node_modules/commando-provider-mongo/index.js:57:92
2020-12-11T04:17:37.521234+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/cursor.js:763:13
2020-12-11T04:17:37.521235+00:00 app[worker.1]:     at handleCallback (/app/node_modules/mongodb/lib/core/cursor.js:31:5)
2020-12-11T04:17:37.521235+00:00 app[worker.1]:     at nextFunction (/app/node_modules/mongodb/lib/core/cursor.js:864:5)
2020-12-11T04:17:37.521236+00:00 app[worker.1]:     at Cursor._next (/app/node_modules/mongodb/lib/core/cursor.js:201:5)
2020-12-11T04:17:37.521236+00:00 app[worker.1]:     at loop (/app/node_modules/mongodb/lib/operations/cursor_ops.js:114:10)
2020-12-11T04:17:37.521237+00:00 app[worker.1]:     at each (/app/node_modules/mongodb/lib/operations/cursor_ops.js:93:18)
2020-12-11T04:17:37.521237+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/operations/cursor_ops.js:103:7
2020-12-11T04:17:37.521237+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/utils.js:677:5
2020-12-11T04:17:37.521238+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/cursor.js:250:9
2020-12-11T04:17:37.521238+00:00 app[worker.1]:     at handleCallback (/app/node_modules/mongodb/lib/core/cursor.js:31:5)
2020-12-11T04:17:37.521238+00:00 app[worker.1]:     at nextFunction (/app/node_modules/mongodb/lib/core/cursor.js:864:5)
2020-12-11T04:17:37.521239+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/core/cursor.js:740:7
2020-12-11T04:17:37.521239+00:00 app[worker.1]:     at done (/app/node_modules/mongodb/lib/core/cursor.js:458:7)
2020-12-11T04:17:37.521242+00:00 app[worker.1]:     at queryCallback (/app/node_modules/mongodb/lib/core/cursor.js:500:20)
2020-12-11T04:17:37.521242+00:00 app[worker.1]:     at /app/node_modules/mongodb/lib/core/cursor.js:545:9
2020-12-11T04:17:37.573892+00:00 heroku[worker.1]: Process exited with status 1
```

**Comment by paulhobbel** [comment]
On which version are you, we fixed this in the latest version

**Comment by BeeBuzz420** [comment]
> On which version are you, we fixed this in the latest version

Im using the latest version. I've been using this provider for the past months and then I had no problem. But then it just happened randomly today when I tried to restart my bot I don't understand why.

**Comment by paulhobbel** [comment]
Can you please specify the following.
- Discord.JS version
- Commando version
- Commando Provider Mongo version

**Comment by BeeBuzz420** [comment]
DJS: v12.5.0
Commando: v0.11.0-dev
Provider: v1.3.0

**Comment by paulhobbel** [comment]
Okay thats interesting, make sure it's also updated in your lock file as this function bas been changed in v1.3.0, it seems like your application still uses v1.2.1 somehow

**Comment by paulhobbel** [comment]
We added a check to allow both Discord.JS v11 and v12 and somehow it still use the old method for your application
https://github.com/paulhobbel/commando-provider-mongo/blob/main/index.js#L57

**Comment by paulhobbel** [comment]
To be sure I'll set up a sample application to test the behaviour to make sure it's not an issue on our side

**Comment by iseizuu** [comment]
I think you should remove `client.guilds.has` because djs v11 is no longer usable (deprecated)

**Comment by Spencer-0003** [comment]
I'm also randomly getting this issue too? My bot worked fine this morning but now it's erroring with this can you remove `client.guilds.has`?

**Comment by paulhobbel** [comment]
Alright will update the package to work from d.js 12+

**Comment by Spencer-0003** [comment]
> 
> 
> Alright will update the package to work from d.js 12+

Thank you!

**Comment by paulhobbel** [comment]
An update will follow today, it has also been update to typescript and I fixed an issue when using sharding

**Comment by notaroomba** [comment]
client.guilds.cache.has?

**Comment by paulhobbel** [comment]
yea will be fixed in an update tomorrow

**Comment by notaroomba** [comment]
ok

**Comment by paulhobbel** [comment]
New version is now up as 2.0.0 to remain semver compliant

**Comment by Spencer-0003** [comment]
Not sure if this is an issue on my end but now I'm getting

```
Error: Cannot find module 'C:\X\node_modules\commando-provider-mongo\index.js'. Please verify that the package.json has a valid "main" entry

**Comment by paulhobbel** [comment]
~~Oh wups, that's my bad. I didn't change the package.json. For a tempfix you can change "main" in package.json to "dist/index.js".

For a reference look at the new package.json. I currently don't have a computer by hand so can't publish the new version yet~~

Patch has been published: `2.0.1`

**Comment by Spencer-0003** [comment]
My bot now errors with

`Error: TypeError: Class constructor SettingProvider cannot be invoked without 'new'`

`client.setProvider(MongoClient.connect(mongo_url, { useNewUrlParser: true, useUnifiedTopology: true }).then(mongoClient => {
    console.log("Connected to database.");
    return new MongoDBProvider(mongoClient, mongo_db);
}).catch(err => {
    throw new Error(err);
}));`

**Comment by paulhobbel** [comment]
Sorry for the bad testing, should be solved now in `2.0.2`

**Comment by Spencer-0003** [comment]
Yeah, my bot works fine now 😃

**Comment by paulhobbel** [comment]
Glad to hear

**Comment by notaroomba** [comment]
It works
